# Generated by Django 3.2.6 on 2023-07-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
    ]
